### ISSUE TITLE
Build macOS kernel collection

### ISSUE THREAD

**Issue by koharin** [vul337/KextFuzz#3]
Hi.
I'm trying to build Kextfuzz following the Readme.md.
```
sudo cp -r ./output/* ./Extensions/
```
I stuck in building macOS kernel collection, above command.
What's output directory and what're in output directory?
I can't find a description or comment about that, so that I can't step into next.

I appreciate if you consider my question.
Thanks for your efforts.

**Comment by ttiinn** [comment]
The output directory is define in ./rewrite/config.json `output_dir`. It is in the working directory by default. The rewritten binary is supposed to be found in this directory.

**Comment by koharin** [comment]
I've found output directory.
Thanks for your instruction.
